# Generated by Django 4.0.5 on 2022-06-12 07:48

from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='Nairobi', max_length=63),
        ),
    ]
