# Generated by Django 4.0.5 on 2022-06-12 08:31

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_project_created_on_project_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}),
        ),
    ]
