# Generated by Django 4.0.5 on 2022-06-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_alter_project_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_voted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='awwards.project')),
                ('profile_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awwards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.CharField(max_length=255)),
                ('project_associated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awwards.project')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awwards.profile')),
            ],
        ),
    ]
