# Generated by Django 4.0.5 on 2022-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_profile_fax_number_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fax_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
