# Generated by Django 4.0.5 on 2022-06-12 13:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_remove_profile_fax_number_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
